// <auto-generated />
using System;
using GyanTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GyanTrack.Api.Migrations
{
    [DbContext(typeof(GyanTrackDbContext))]
    [Migration("20260303030952_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MarksAwarded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOptionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttemptID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SelectedOptionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Option", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("OptionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TestID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TemplateID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.TestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CopyPasteCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SystemScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TabSwitchCount")
                        .HasColumnType("int");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WindowFocusLossCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InternID");

                    b.HasIndex("TestID");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.AssignmentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceWeight")
                        .HasColumnType("int");

                    b.Property<int>("CommunicationWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalWeight")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("SubjectID");

                    b.ToTable("AssignmentTemplates", t =>
                        {
                            t.HasCheckConstraint("CK_Weightage_Sum", "TechnicalWeight + CommunicationWeight + AttendanceWeight = 100");
                        });
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.EvaluatorIntern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<int>("InternID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InternID");

                    b.HasIndex("EvaluatorID", "InternID")
                        .IsUnique();

                    b.ToTable("EvaluatorInterns");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.EvaluatorRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttemptID");

                    b.HasIndex("EvaluatorID");

                    b.ToTable("EvaluatorRemarks");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.PerformanceScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AttendanceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommunicationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<int>("InternID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TechnicalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("InternID");

                    b.HasIndex("TemplateID");

                    b.ToTable("PerformanceScores");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectName")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Evaluator", b =>
                {
                    b.Property<int>("EvaluatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("EvaluatorID");

                    b.ToTable("Evaluators");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Intern", b =>
                {
                    b.Property<int>("InternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("InternID");

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Answer", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Assessments.TestAttempt", "TestAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Assessments.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Assessments.Option", "SelectedOption")
                        .WithMany("Answers")
                        .HasForeignKey("SelectedOptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Option", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Assessments.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Question", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Assessments.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Test", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.Evaluator", "CreatedByEvaluator")
                        .WithMany("CreatedTests")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Evaluations.AssignmentTemplate", "Template")
                        .WithMany("Tests")
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByEvaluator");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.TestAttempt", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.Intern", "Intern")
                        .WithMany("TestAttempts")
                        .HasForeignKey("InternID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Assessments.Test", "Test")
                        .WithMany("TestAttempts")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intern");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.AssignmentTemplate", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.Admin", "CreatedByAdmin")
                        .WithMany("CreatedTemplates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Users.Evaluator", "Evaluator")
                        .WithMany("AssignedTemplates")
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Evaluations.Subject", "Subject")
                        .WithMany("AssignmentTemplates")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Evaluator");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.EvaluatorIntern", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.Evaluator", "Evaluator")
                        .WithMany("AssignedInterns")
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Users.Intern", "Intern")
                        .WithMany("AssignedEvaluators")
                        .HasForeignKey("InternID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.EvaluatorRemark", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Assessments.TestAttempt", "TestAttempt")
                        .WithMany("EvaluatorRemarks")
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Users.Evaluator", "Evaluator")
                        .WithMany("GivenRemarks")
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.PerformanceScore", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.Evaluator", "Evaluator")
                        .WithMany("PerformanceScores")
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Users.Intern", "Intern")
                        .WithMany("PerformanceScores")
                        .HasForeignKey("InternID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GyanTrack.Api.Models.Evaluations.AssignmentTemplate", "Template")
                        .WithMany("PerformanceScores")
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Intern");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Admin", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("GyanTrack.Api.Models.Users.Admin", "AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Evaluator", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.User", "User")
                        .WithOne("Evaluator")
                        .HasForeignKey("GyanTrack.Api.Models.Users.Evaluator", "EvaluatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Intern", b =>
                {
                    b.HasOne("GyanTrack.Api.Models.Users.User", "User")
                        .WithOne("Intern")
                        .HasForeignKey("GyanTrack.Api.Models.Users.Intern", "InternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Option", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestAttempts");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Assessments.TestAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("EvaluatorRemarks");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.AssignmentTemplate", b =>
                {
                    b.Navigation("PerformanceScores");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Evaluations.Subject", b =>
                {
                    b.Navigation("AssignmentTemplates");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Admin", b =>
                {
                    b.Navigation("CreatedTemplates");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Evaluator", b =>
                {
                    b.Navigation("AssignedInterns");

                    b.Navigation("AssignedTemplates");

                    b.Navigation("CreatedTests");

                    b.Navigation("GivenRemarks");

                    b.Navigation("PerformanceScores");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.Intern", b =>
                {
                    b.Navigation("AssignedEvaluators");

                    b.Navigation("PerformanceScores");

                    b.Navigation("TestAttempts");
                });

            modelBuilder.Entity("GyanTrack.Api.Models.Users.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Evaluator");

                    b.Navigation("Intern");
                });
#pragma warning restore 612, 618
        }
    }
}
