// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInternSystem.Data;

#nullable disable

namespace GyanTrack.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvaluatorRemark", b =>
                {
                    b.Property<int>("RemarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemarkID"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RemarkID");

                    b.HasIndex("AttemptID");

                    b.HasIndex("EvaluatorID");

                    b.ToTable("EvaluatorRemarks");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Attempts.Answer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal>("MarksAwarded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOptionID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("AttemptID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SelectedOptionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Attempts.TestAttempt", b =>
                {
                    b.Property<int>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttemptID");

                    b.HasIndex("InternID");

                    b.HasIndex("TestID");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Evaluation.PerformanceScore", b =>
                {
                    b.Property<int>("ScoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreID"));

                    b.Property<decimal>("AttendanceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommunicationScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<int?>("InternID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TechnicalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TemplateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScoreID");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("InternID");

                    b.HasIndex("TemplateID");

                    b.ToTable("PerformanceScores");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Mapping.EvaluatorIntern", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<int>("InternID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("InternID");

                    b.ToTable("EvaluatorInterns");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Templates.AssignmentTemplate", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<int>("AttendanceWeight")
                        .HasColumnType("int");

                    b.Property<int>("CommunicationWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TemplateID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("SubjectID");

                    b.ToTable("AssignmentTemplates");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Templates.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Tests.Option", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("OptionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Tests.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionID");

                    b.HasIndex("TestID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Tests.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TestID");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("TemplateID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.Evaluator", b =>
                {
                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvaluatorID");

                    b.ToTable("Evaluators");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.Intern", b =>
                {
                    b.Property<int>("InternID")
                        .HasColumnType("int");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InternID");

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EvaluatorRemark", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Attempts.TestAttempt", "TestAttempt")
                        .WithMany()
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Users.Evaluator", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Attempts.Answer", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Attempts.TestAttempt", "TestAttempt")
                        .WithMany()
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Tests.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Tests.Option", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Attempts.TestAttempt", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Tests.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intern");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Evaluation.PerformanceScore", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.Evaluator", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Users.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartInternSystem.Models.Templates.AssignmentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Evaluator");

                    b.Navigation("Intern");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Mapping.EvaluatorIntern", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.Evaluator", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Users.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Templates.AssignmentTemplate", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Users.Evaluator", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Templates.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Evaluator");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Tests.Option", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Tests.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Tests.Question", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Tests.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Tests.Test", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.Evaluator", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInternSystem.Models.Templates.AssignmentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.Admin", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("SmartInternSystem.Models.Users.Admin", "AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.Evaluator", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("SmartInternSystem.Models.Users.Evaluator", "EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartInternSystem.Models.Users.Intern", b =>
                {
                    b.HasOne("SmartInternSystem.Models.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("SmartInternSystem.Models.Users.Intern", "InternID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
